name: LoopBack
favicon: null
layout_spectrum: 0.6914582645986229
typography_spectrum: 0.04120145412161946
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.0033431677147746086
  lightness: 0.26173589820973575
  saturation: 0.06510535161942244
  rhythmicContrast: 0.7167354405391961
purpose: []
